"""empty message

Revision ID: 17ea8c1be824
Revises: 
Create Date: 2018-02-24 17:41:52.613000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17ea8c1be824'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drugType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accountNo', sa.String(length=50), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('accountMoney', sa.REAL(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('saleCount', sa.Integer(), nullable=False),
    sa.Column('price', sa.REAL(), nullable=False),
    sa.Column('desc', sa.String(length=500), nullable=False),
    sa.Column('drugTypeId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drugTypeId'], ['drugType.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('saleCount', sa.Integer(), nullable=False),
    sa.Column('saleMoney', sa.REAL(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('accountId', sa.Integer(), nullable=True),
    sa.Column('drugId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accountId'], ['account.id'], ),
    sa.ForeignKeyConstraint(['drugId'], ['drug.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stockDate', sa.DateTime(), nullable=False),
    sa.Column('stockPrice', sa.REAL(), nullable=False),
    sa.Column('stockCount', sa.Integer(), nullable=False),
    sa.Column('stockMoney', sa.REAL(), nullable=False),
    sa.Column('drugId', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drugId'], ['drug.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock')
    op.drop_table('sale')
    op.drop_table('drug')
    op.drop_table('account')
    op.drop_table('drugType')
    # ### end Alembic commands ###
